# Author: Hunter Jones

# Set base image and instantiate Ubuntu (noble=24.04, jammy=22.04)
FROM ubuntu:22.04
LABEL maintainer="Hunter Jones <joneshu2@msu.edu>"
LABEL description="Docker Image for pizza management application"

# Update and install Ubuntu and install pip
RUN apt update
RUN apt-get update -qq
RUN apt -y install python3-pip
RUN apt -y install vim
RUN mkdir /app
COPY . /app
WORKDIR /app
RUN pip install --no-cache-dir -r requirements.txt


# Open port 8080 for flask app instead of default 5000 and set environment variable
EXPOSE 8080
ENV PORT=8080

# Set as Development Environment
ENV FLASK_ENV=development

# RUN Gunicorn
CMD exec python3 app.py